/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EventInformation {
  metadata: {
    /**
     * ISO 8601 format date and time when the event starts.
     */
    eventStart: string;
    /**
     * Duration in HH:MM:SS format to the next state change.
     */
    timeToNextEvent: string;
    /**
     * Current running clock in HH:MM:SS format.
     */
    runningClock: string;
    [k: string]: unknown;
  };
  state: {
    /**
     * The current state of the event.
     */
    currentState:
      | "Pre Trial Start"
      | "Trial Start"
      | "Trial End"
      | "Delay Start"
      | "Delay End"
      | "In Transit"
      | "Mistrial"
      | "RTB";
    delay?: {
      /**
       * The reason for the delay.
       */
      reason:
        | "vendor issues causing delay in trial execution"
        | "Unauthorized craft enters OP area (NPC = non-personnel craft)"
        | "Boat experiences network drops or software crashes"
        | "Boat loses power, must be towed out of OP area";
      /**
       * Predicted resolution time in ISO 8601 format.
       */
      predictedResolutionTime: string;
      [k: string]: unknown;
    } | null;
    [k: string]: unknown;
  };
  transcription: {
    /**
     * Time-ordered transcription feed.
     */
    speechToText: string[];
    [k: string]: unknown;
  };
  performanceMetrics: {
    timeToTranscribePerToken: {
      /**
       * Minimum time to transcribe per token.
       */
      min: number;
      /**
       * Maximum time to transcribe per token.
       */
      max: number;
      /**
       * Average time to transcribe per token.
       */
      avg: number;
      [k: string]: unknown;
    };
    timeToInference: {
      /**
       * Minimum time to inference.
       */
      min: number;
      /**
       * Maximum time to inference.
       */
      max: number;
      /**
       * Average time to inference.
       */
      avg: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
